package TRY_Catch;

public class try1 
{
	public static void main(String[] args)
	{
	  
		int a=1;
		
		int b=0;
		
		int c;
		
		try 
		{
			c=b/a;
		}
		catch(ArithmeticException e)
		{
			
		}
	 
		
		
	}
	
	
}
